% Partial Run for Mara's computer - linux
cd ./firePT_F15HS_MAXSS_OS
firePT_F15HS_MAXSS_OS
cd ../firePT_F15HS_MAXSS_FS
firePT_F15HS_MAXSS_FS
cd ../firePT_F15HS_BIRS_OS
firePT_F15HS_BIRS_OS
cd ../firePT_F15HS_BIRS_FS
firePT_F15HS_BIRS_FS
cd ../firePT_F15HS_PDEN_OS
firePT_F15HS_PDEN_OS
cd ../firePT_F15HS_PDEN_FS
firePT_F15HS_PDEN_FS
cd ../firePT_F15LS_MAXSS_OS
firePT_F15LS_MAXSS_OS
cd ../firePT_F15LS_MAXSS_FS
firePT_F15LS_MAXSS_FS
cd ../firePT_F15LS_BIRS_OS
firePT_F15LS_BIRS_OS
cd ../firePT_F15LS_BIRS_FS
firePT_F15LS_BIRS_FS
cd ../firePT_F15LS_PDEN_OS
firePT_F15LS_PDEN_OS
cd ../firePT_F15LS_PDEN_FS
firePT_F15LS_PDEN_FS
cd ../firePT_F7HS_MAXSS_OS
firePT_F7HS_MAXSS_OS
cd ../firePT_F7HS_MAXSS_FS
firePT_F7HS_MAXSS_FS
cd ../firePT_F7HS_BIRS_OS
firePT_F7HS_BIRS_OS
cd ../firePT_F7HS_BIRS_FS
firePT_F7HS_BIRS_FS
cd ../firePT_F7HS_PDEN_OS
firePT_F7HS_PDEN_OS
cd ../firePT_F7HS_PDEN_FS
firePT_F7HS_PDEN_FS
cd ../firePT_F7LS_MAXSS_OS
firePT_F7LS_MAXSS_OS
cd ../firePT_F7LS_MAXSS_FS
firePT_F7LS_MAXSS_FS
cd ../firePT_F7LS_BIRS_OS
firePT_F7LS_BIRS_OS
cd ../firePT_F7LS_BIRS_FS
firePT_F7LS_BIRS_FS
cd ../firePT_F7LS_PDEN_OS
firePT_F7LS_PDEN_OS
cd ../firePT_F7LS_PDEN_FS
firePT_F7LS_PDEN_FS